name: Github PR Merge Check
description: This External Adapter will enable a ChainLink node to check whether or not a pull request has been merged. If a PR has been merged then this external adaptor will return a 404. If a PR has NOT been merged then this external adaptor will return a 206... I know that is confusing but this is according to Github Documentation. 
node_identifier: Github_PR_Check_Merge
platforms:
  - Docker
  - AWS Lambda
  - GCP Functions
data_sources:
  - name: GitHub
  - url: https://cloud.google.com/

